# Generated by Django 3.1.2 on 2021-11-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=400)),
                ('summary', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('posts', models.ManyToManyField(blank=True, related_name='authors', to='posts.Post')),
            ],
        ),
    ]
